#!/bin/bash
cmd=`which $0`
cmddir=${cmd%/*}
subcmd="$cmddir/../libexec/mapit_tools/"$1

if [ "$#" -le 0 ]; then
    echo "no parameters given"
    exit
fi

if [[ -x "$subcmd" ]]
then
    $subcmd "${@:2}"
else
    echo "mapit subcommand '$1' does not exist"
fi
